name: clovis_two
description: Learn best practice of flutter data list widgets and files & folders management
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  adaptive_layout: ^0.1.7
  awesome_dialog: ^2.2.1
  blur: ^3.1.0
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  easy_sidemenu: ^0.3.1
  flutter_dropzone: ^3.0.5
  flutter_jailbreak_detection: ^1.8.0
  flutter_local_notifications: ^9.7.0
  flutter_native_splash: ^2.2.6
  flutter_secure_screen: ^0.0.1
  flutter_svg: ^1.1.1+1
  get: ^4.6.5
  get_storage: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.6.0
  logger: ^1.1.0
  lottie: ^1.4.1
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  permission_handler: '>=8.2.6 <10.0.0'
  retrofit: '>=3.0.0 <4.0.0'
  shimmer: ^2.0.0
  mask_text_input_formatter: ^2.3.0
  toast: ^0.3.0
  fluttertoast: ^8.1.1
  units_converter: ^2.0.0
  elegant_notification: ^1.6.0
  chewie: ^1.3.4
  video_player: ^2.4.5
  carousel_slider: ^4.1.1
  photo_view: ^0.14.0
  video_player_web: ^2.0.12
  fl_chart: ^0.55.0
  intl: ^0.17.0
  firebase_core: ^2.3.0
  fast_rsa: ^3.5.1
  firebase_remote_config: ^3.0.6
  firebase_crashlytics: ^3.0.6

  flutter:
    sdk: flutter

dev_dependencies:
  build_web_compilers: ^3.2.4
  flutter_gen_runner: 5.1.0+1
  flutter_lints: ^2.0.1
  freezed: ^2.2.1
  hive_generator: ^2.0.0
  json_converter: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0'
  json_serializable: '>4.4.0'

  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/loader/
    - assets/images/
    - assets/images/global/
    - assets/images/illustration/
  fonts:
    - family: Maison Neue
      fonts:
        - asset: assets/fonts/maisonneue_ext_book.ttf
        - asset: assets/fonts/maisonneue_ext_demi.ttf
          weight: 600
        - asset: assets/fonts/maisonneue_ext_bold.ttf
          weight: 700
    - family: Hauora
      fonts:
        - asset: assets/fonts/hauora_book.ttf
        - asset: assets/fonts/hauora_demi.ttf
          weight: 600
        - asset: assets/fonts/hauora_bold.ttf
          weight: 700